/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.*;

public class Library {
    public boolean someLibraryMethod() {
        List<Boolean> booleans = new ArrayList<>();
        booleans.addAll(Collections.nCopies(256, Boolean.TRUE));
        return booleans.get(256);
    }
}
