/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.MongoClient;
import java.util.Collections;

import java.net.UnknownHostException;

public class Library {
    public boolean someLibraryMethod() {
        // Based on https://jira.mongodb.org/browse/JAVA-2434
        MongoClient mongo = new MongoClient("localhost", 27017);
        DB db = mongo.getDB("testdb");
        DBCollection collection = db.getCollection("dummyColl");
        collection.insert(Collections.emptyList());
        return true;
    }
}
